{% set name = "pysam" %}
{% set version = "0.23.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pysam-{{ version }}.tar.gz
  sha256: 9ebcb1f004b296fd139b103ec6fd7e415e80f89f194eb7d0d972ac6d11bbaf24
  patches:
    - patches/0001-Unvendor-deps.patch

build:
  number: 0
  # https://github.com/samtools/htslib/issues/86
  skip: True  # [win]
  skip: True  # [py<38]
  script_env:
    # This is the default, but it's preferable to be explicit.
    - HTSLIB_MODE=shared
  script:
    # Delete samtools/lz4 just to make sure they are not used/compiled by accident.
    - rm -rf samtools/lz4
    - {{ PYTHON }} -m pip install . -v --no-build-isolation --no-deps

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - patch
    - make
  host:
    - python
    - pip
    - setuptools >=59.0
    - wheel
    - cython >=3,<4
    # These are required for the vendored htslib.
    - libcurl 8
    - bzip2 {{ bzip2 }}
    - xz {{ xz }}
    - libdeflate 1.22
    # Only required for libcrypto.
    # On macOS, links to libSystem
    - openssl  {{ openssl }}  # [linux]
    - lz4-c 1.9
    # These are required for the vendored htslib, bcftools and samtools.
    - zlib {{ zlib }}
  run:
    - python
    - lz4-c  # pin through run_exports
    - {{ pin_compatible('libcurl') }}
    - bzip2  # pin through run_exports
    - xz  # pin through run_exports
    - zlib  # pin through run_exports
    - openssl  # [linux]
    - libdeflate  # pin through run_exports

test:
  imports:
    - pysam
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # All tests are required 'samtools', 'bcftools' or 'htslib' which are not in Conda yet or are incompatible.
    # Skip them until those packages will released in Conda
    # - REF_PATH=':' pytest gh_src/tests -v {{ skip_test_file }}
  requires:
    - pip

about:
  home: https://github.com/pysam-developers/pysam
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Pysam is a Python package for reading, manipulating, and writing genomics data such as SAM/BAM/CRAM and VCF/BCF files. It's a lightweight wrapper of the HTSlib API, the same one that powers samtools, bcftools, and tabix.
  description: >
    Pysam is a python module for reading and manipulating files in the SAM/BAM format.
    The SAM/BAM format is a way to store efficiently large numbers of alignments (Li 2009),
    such as those routinely created by next-generation sequencing methods.
  dev_url: https://github.com/pysam-developers/pysam
  doc_url: https://pysam.readthedocs.io

extra:
  skip-lints:
    - patch_unnecessary